runtime: python
application: codesf-suggest
api_version: 1
version: 1a
threadsafe: true


runtime_config:
  python_version: python27

handlers:
- url: .*  # This regex directs all routes to main.app
  script: codesf_suggest.main.app


